### ISSUE TITLE
Eliminate prefixes from the label

### ISSUE THREAD

**Issue by koppor** [latextemplates/biblatex-lni#3]
Desired output:

    Zwei Autoren: Abel und Bibel [AB00] und van der Aalst und Weske [AW13].

Got output:

    Zwei Autoren: Abel und Bibel [AB00] und van der Aalst und Weske [vdAW13]

I achieved the desired output with

```
\usepackage[           
  backend=biber,
  style=alphabetic,
  useprefix     = false  
]{biblatex}
\usepackage{hyperref}
\addbibresource{LNI-examples.bib}
\makeatletter
%Do not put "vd" in the label, but put it at "\citeauthor"
%Source: http://tex.stackexchange.com/a/30277/9075
\AtBeginDocument{\toggletrue{blx@useprefix}}
\AtBeginBibliography{\togglefalse{blx@useprefix}}
\makeatother
```

This hack (toggle true/false), however, does not work with the current bbx.

In the bibliography it should be

    [AW13] van der Aalst, W.M.P.; Weske, M.:

(if it is "Van der Aalst, W.M.P.; Weske M.", it is also OK if van der Aalst appears first)

instead of

    [vdAW13] Aalst, W.M.P. van der; Weske, M.:

**Comment by georgd** [comment]
This should be fixed in the blx file. There's a setting for prefixes in the
label definition.
I'll have a look at it later.

Oliver Kopp <notifications@github.com> schrieb am Mo., 10. Okt. 2016, 22:51:

**Comment by georgd** [comment]
Fixed by https://github.com/latextemplates/biblatex-lni/commit/d523a0bfc71fe1b975ea9d46165ea32f3d2f28c4

**Comment by koppor** [comment]
:+1: - I'm curently unsure, whether it should be "[AG13] Van der Aalst, W.M.P.; von Goethe" - meaning: First author in the author list capitalized. (Maybe I was wrong regarding that part in my description)

**Comment by georgd** [comment]
If there’s no hint in the official template what does the actual practise look like? It might be biased by the software used to produce the articles, though.

**Comment by koppor** [comment]
In our case, we directly take the PDF produced by pdflatex. No further
processing involved.

I try to look at old LNI books...
